### ISSUE TITLE
Needs better introduction

### ISSUE THREAD

**Issue by GrantMeStrength** [lobe/lobe-adafruit-kit#2]
I ordered the Adafruit kit, and there was no guidance on:

* Assembling the hardware
* What's on the SD card (turns out, nothing, you need to install the Pi OS on it)

A summary that covered this, and a step-by-step list that linked to existing pages (installing the camera, connecting the fan, downloading the Pi OS) would help.

I also found it a little odd that while I had all this hardware, instead of setting it up I was launched right into using Lobe. Since the Pi updates and installations take so long to perform, it would be a better use of time to set up the Pi, start off the installations, and while that was happening downloading train Lobe. )Or better yet, learn about Lobe but then make use of a predefined Lobe model)

**Comment by JakeCohenMicrosoft** [comment]
Hi John, appreciate the feedback. I agree setting up the hardware and SD card does take some time. Did you find the links to the Adafruit tutorials? They have step by step instructions setting up the hardware and SD card. 

We wanted to start with Lobe to get folks introduced to machine learning. But I like the idea of setting up the hardware and using Lobe while it installs!

Can I set up a quick chat with you to talk more about the kit and your experience getting it set up?

**Comment by chriskosovich** [comment]
I have had success with setup following the Adafruit tutorials all the way up to uploading a model. It seems the github files are for rock paper scissors model that seem different from the adafruit tutorial I was following. Just mentioning this because I may have done something incorrect or not understanding yet the upload of the model.

**Comment by chriskosovich** [comment]
Ok...after some trial and error I am able to now play rock, paper, scissors with the machine! The Adafruit tutorials were helpful, but I think I needed to blend a couple of the tutorials together to make things work. @JakeCohenMicrosoft, I can share some feedback if it is helpful.

**Comment by JakeCohenMicrosoft** [comment]
congrats on getting it set up Chris! Yes, I would love to chat and get your feedback. Feel free to pick a time that works best for you: https://calendly.com/lobeai/30min. Tomorrow would be great, if not early next week.

**Comment by JakeCohenMicrosoft** [comment]
It was great chatting with you today @GrantMeStrength  and @chriskosovich! We will look into improving our GitHub and tutorial instructions to make it more clear how to get the HW set up and work through the tutorials.
